name: Testing Ubuntu 22.04

on:
  pull_request:
    branches: ["**"]
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check_backup_test
        run: docker build -f ./tests/ubuntu_2204/check_backup .
      - name: testing
        run: docker build -f ./tests/ubuntu_2204/dockerfile .
