name: Testing openwrt(apk)

on:
  pull_request:
    branches: ["**"]
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: testing
        run: docker build -f ./tests/openwrt_apk/dockerfile .
