name: Ubuntu Test

on:
  pull_request:
    branches: [ "**" ]
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: change url
      run: sh run.sh
    - name: run update
      run: sudo apt-get update
